README.md

Since the package name is not immediately obvious for someone on the GitHub page

Add npm name to the README

---

lib/client.js
test/client.js

If the callback has 2-arity, we assume the first param is `err` and use it when the API returns an `error.list`. This allows for idiomatic callback handling like:
```node
client.users.list(function(err, d) { ... });
```
Additionally this pr adds support for objects in client construction:
```node
var client = new Client({ appId: 'foo', appApiKey: 'bar' });
```
fixes https://github.com/intercom/intercom-node/issues/15

Allow err params in callbacks and support objects in Client

---

lib/admin.js
lib/bulk.js
lib/client.js
lib/company.js
lib/contact.js
lib/conversation.js
lib/counts.js
lib/event.js
lib/message.js
lib/note.js
lib/segment.js
lib/tag.js
lib/user.js
test/admin.js
test/bulk.js
test/client.js
test/company.js
test/contact.js
test/conversation.js
test/counts.js
test/event.js
test/index.js
test/message.js
test/note.js
test/segment.js
test/tag.js
test/user.js

This drops in optional support for promises:
```node
let client = new Client('foo', 'bar').usePromises()
client.users.create({ email: 'foo@bar.com' }).then(function (r) {
// ...
});
```
Due to the lack of implicit return, I've had to modify all of the models. As I result I've also rewritten all of the tests into promise format.
This shouldn't be a breaking change, but will probably be a major release.
The actual new promise code: https://github.com/intercom/intercom-node/pull/47/files#diff-50cfa59973c04321b5da0c6da0fdf4feR43
I have not looked into ES7 async stuff. Once we have an API in place we can iterate on that if necessary.

Promises support

---

lib/client.js
package.json

Here is a the change just dropping in `Bluebird` for promises - you'll see that it's already added helpful output
I kept the client the same as you had before but it is following the promise constructor anti-pattern. A different approach would be to just promisifying the `unirest` lib if the client is using promises - this would lead to cleaner code and you won't have to reinvent the wheel with `if (err) reject.. else resolve`. Also it prevents edge cases like the `unirest` lib throwing an error synchronously or multiple success values.
[Check this out](http://bluebirdjs.com/docs/anti-patterns.html#explicit-construction-anti-pattern) to see more details on the anti-pattern

Refactored client to use Bluebird for promises

---

lib/client.js
test/client.js

We can deprecate the `usePromises` flag after this.
fixes https://github.com/intercom/intercom-node/issues/52

default to returning a promise when callbacks are absent

---

README.md

* add a note about required params (it's not intuitive that `created_at` would be required)
* add `metadata` in the example. It took me a while to find how to pass through metadata (I had to find the REST  API documentation)

Update README - clarify events.create API

---

README.md

Original `usePromises` method was deprecated in #86

Update README to reflect updated promise behavior

---

README.md
lib/scroll.js
test/scroll.js

I've started using users.scroll but I had a few issues with this method.
First, unlike other methods of the API, this one didn't return a promise, which is inconsistent and made my life harder :-)
Secondly, this method gives me no control on when it will scroll. Basically, once started, it will scroll until the end of the list of users. In my use-case, I wanted to store in a DB a few info about the users I retrieved:
```js
client.users.scroll.each({}, function (res) {
res.body.users.forEach((user) => {
remoteDb.store(user.id, user.email);
});
});
```
Doing this means that I will have a potentially HUGE number of concurrent queries to my database, and large memory consumption as well.
This patch makes it possible to return a Promise from the callback, and users.scroll will wait for this …

Make users.scroll return a promise and wait for inner promises

---

lib/admin.js

Right now you can't get an admin from the API. You can only list them, but that will not return a full admin object.
Because the admin object is the only to get the avatar of an admin this is very needed,
This creates support for the `/admins/:id`, https://developers.intercom.com/reference#view-an-admin

Add support for viewing an admin

---

lib/client.js
test/base-url.js

Basically a simple change, to make the client more testable. (For example, work against a stub server).

Add ability to change intercom base url, for testing purposes

---

lib/scroll.js

The `each` function of a scroll should set `scroll_param` (not `scroll_params`) to `undefined`.

Fix: properly reset scroll_param on new scroll

---

lib/client.js
package.json
test/admin.js
test/base-url.js
test/bulk.js
test/client.js
test/company.js
test/contact.js
test/conversation.js
test/counts.js
test/event.js
test/message.js
test/note.js
test/scroll.js
test/segment.js
test/tag.js
test/user.js
test/visitor.js

The current HTTP client, [`unirest`](https://github.com/Mashape/unirest-nodejs) depends on a library that has a security advisory alert. [I submitted a PR to them](https://github.com/Kong/unirest-nodejs/pull/112), but it doesn't look like the library is maintained any more. 
This removes `unirest` and introduces [`request`](https://github.com/request/request) which is an actively maintained http client. I removed the duplication of headers / auth by introducing a `request()` method. This change will fix https://github.com/intercom/intercom-node/issues/163.
This does slightly change the response however — request does not include a `status` key in the response, only `statusCode` key. I left the response alone and updated the tests. It would be possible to merge in a status key if required, …

Remove Unirest from the codebase as it's unmaintained

---

lib/index.js
lib/user-data.js
package.json
test/user-data.js

This adds a `UserData` class to the Node client, which is exposed through the client like so:
```javascript
const { UserData } = require('intercom-client');
const settings = {
verificationSecret: 'abc123',
app_id: 'xyz789',
user_id: 1,
email: 'jess@intercom.io',
name: 'Jess OBrien',
company: {
id: 123,
name: 'Intercom'
}
};
const userData = new UserData(settings);
res.send(userData.json());
```
It returns an escaped json object, including the `user_hash` required for Identity Verification. You can call window.Intercom(`boot`) on the client side with the data returned.

Add a user-data class for generating intercomSettings

---

.travis.yml
lib/client.js
test/errors.js
yarn.lock

When no response is received (i.e. request error) there's no `data` here:
https://github.com/intercom/intercom-node/blob/8918db291ac15144c4d18148356ef5ec93088df8/lib/client.js#L141
This is due to the errors being ignored from `request` here:
https://github.com/intercom/intercom-node/blob/8918db291ac15144c4d18148356ef5ec93088df8/lib/client.js#L68-L70
and here:
https://github.com/intercom/intercom-node/blob/8918db291ac15144c4d18148356ef5ec93088df8/lib/client.js#L73
This PR has:
* Failing tests for request errors (using `nock` and [`replyWithError`](https://github.com/bookcreator/intercom-node/blob/bb2433994698a770dbd080617d3e4b2e8a84c7c3/test/errors.js#L12)).
* More tests for response errors (unauthorised 401s and rate limit 429s).
* Fix for #169 (and fixes #189) - by passing the error …

Fix for #169 (TypeError: Cannot read property 'error' of undefined)

---

test/client.js
test/errors.js
yarn.lock

Also closes #195 (as this also includes that fix).
@choran apologies for leaving the `.only` in!

Fix for failing test

---

README.md
lib/user.js
test/user.js

Closes #194.
Change summary:
* Renamed `users.delete` to `users.archive`
* Deprecated old `users.delete`
* Added tests for permanently deleting a user
* Implemented permanent user deletion
* Update docs

Support for permanently delete a user

---

.circleci/config.yml

We currently aren't running any tests in production against this repo on Circle.
This adds the configuration to run tests against any build.

Migrating to CircleCI 2.0

---

package.json

Sinon doesn't need to be a prod dependency, the only place you use it is here: https://github.com/intercom/intercom-node/blob/4bd04979a0a0ba962d0f396fba9bf4c39f2ebefd/test/user-data.js

chore: demote sinon to dev dependencies

---

README.md
lib/user.js
test/user.js

Similar to https://github.com/intercom/intercom-go/issues/44 - it's a pain to do two calls to delete a user by `user_id`.
Uses the existing `find` and `requestPermanentDeletion` endpoints to do permanent deletion by `user_id` (or `email`).

Implemented permanent delete user by params endpoint

---

gulpfile.js
lib/client.js
package.json
yarn.lock

There's a prototype pollution vulnerability in `lodash.merge`. The recommended solution is to just use the latest version of lodash: https://github.com/lodash/lodash/issues/4171#issuecomment-457784502
Also fixed a couple of issues breaking the build:
- `nsp` has been [shut down since 9/30](https://www.npmjs.com/package/nsp). I removed it from the gulp prepublish task since it is breaking the build and throwing network errors related to a server not being reachable
- `natives` on version `1.1.3` is breaking the gulp build, upgrading it solves this. On a side note, [natives is deprecated](https://www.npmjs.com/package/natives) and should be replaced with `graceful-fs` eventually.
- Replaced `lodash.merge` with `lodash`
- Upgraded `natives` to `1.1.6`
- …

fix(*): Upgrade natives, lodash, and remove nsp

---

yarn.lock

This is a secondary dependency, pulled in from [`request` version `2.83.0`](https://github.com/intercom/intercom-node/blob/39a445f731d6146e1fe6ba82dbe0d890955573ac/package.json#L24), which [requires](https://github.com/request/request/blob/dd427d7aa0177a876da69f82801bf0c63a855310/package.json#L48) `stringstream` `~0.0.5`. I updated using `yarn upgrade stringstream@~0.0.5`.
https://github.com/intercom/intercom-node/blob/39a445f731d6146e1fe6ba82dbe0d890955573ac/package.json#L24
Fixes https://github.com/intercom/intercom/issues/143632

bump stringstream from 0.0.5 to 0.0.6

---

package.json
yarn.lock

Multiple vulnerabilities were found in some of the dependencies:
https://github.com/intercom/intercom/issues/145614
https://github.com/intercom/intercom/issues/145849
https://github.com/intercom/intercom/issues/144880
https://github.com/intercom/intercom/issues/144877
https://github.com/intercom/intercom/issues/144876
Upgrading `lodash` and `request` dependencies to point releases. Upgrading dev dependencies `gulp-instanbul` , `gulp-plumber` and `sinon` to point, or major releases.

Upgrading dependencies to remove vulnerabilities

---

README.md

To more clearly document how to specify which API version an API call should use. It looks like this is a point of confusion (see https://github.com/intercom/intercom-node/pull/227 for an example)
Adds an example of using API version 1.2 to the README

Add example of how to specify API version to README

---

README.md

The sdk doesn't support API V2.2
Updated the readme

add api 2.2 warning on readme

---

README.md
lib/admin.js
test/admin.js

To enable the admin "away" endpoint 
Added API endpoint for the "away" endpoint as documented here: https://developers.intercom.com/intercom-api-reference/reference#set-admin-away-mode

enable updating admin away mode and reassignment settings

---

README.md
package.json

- Cleanup readme and add maintenance message.
- Bump version for release

update readme and bump version to 2.11.1

---

.circleci/config.yml
lib/common/common.types.ts
lib/contact.ts
lib/conversation.ts

- To be compatible with older `TS` versions `->` `3.X`
- By simplifying `Search` type

Simplify types to be compatible with TS v3.X

---

README.md
lib/client.ts
lib/index.ts
lib/visitor.ts
lib/visitor/visitor.types.ts
test/visitor.ts

- Add Visitors
- Tests
- Func
- Doc

Add Visitors

---

lib/contact.ts
lib/conversation.ts
package.json
test/contact.ts
tsconfig.json

To make it possible to create Contact either with `external_id` or `email`
Closes #308
Closes #309 
- Add `email` param to `createUser`
- Fix test

Fix no email in creating contact params

---

README.md
lib/client.ts
lib/subscription.ts
test/integration/subscriptions.test.ts
test/unit/subscription.test.ts

Because I need this functionality in my application and I want to use the `intercom-node` SDK instead of accessing the API directly.
I created `subscriptions` on the `Client` and a `listTypes` function to list all subscription types. I tried to be consistent with other parts of the client (e.g. `segments`)

Implement the list all subscripition types functionality

---

lib/conversation/conversation.types.ts

Fix typo in Enum

---

README.md

For me, as a user of `intercom-node` package, when I open README.md, the first thing I need to see, is how to install and use this package.
If I ever happen to need to contribute to this package, I will probably look elsewhere; a CONTRIBUTING.md file probably.
But for now, just to make it easier for other developers to follow the usage guide, I moved it to the end of README.md, next to **Pull Requests** section
-- Not Applicable --

Move contribution-related topics altogether to the end of README.md

---

README.md
lib/contact/contact.types.ts
lib/conversation.ts
test/unit/conversation.test.ts

```
Promise { <pending> }
> {
type: 'conversation.list',
pages: {
type: 'pages',
next: {
page: 3,
starting_after: 'WzE2NzAyNTE1ODAwMDAsNjQ2MTk3MDAwMDU2MDYsM10='
},
page: 2,
per_page: 20,
total_pages: 86
},
```

Update conversation list to use 2.6 cursor pagination

---

lib/index.ts
lib/message.ts
test/integration/messages.test.ts
test/unit/message.test.ts

Updates spelling from Recepient to Recipient
closes #352
Fixes a typo
Renaming of some types. Should be considered a **Breaking Change**

Fix typo in Recepient and RecepientType

---

README.md
lib/conversation.ts
package.json
test/integration/conversations.test.ts
test/integration/integration.test.ts
test/unit/conversation.test.ts

Add typings to [reflect field change in 2.6](https://developers.intercom.com/intercom-api-reference/v2.6/reference/changelog#create-conversation-payload-consistency) 
Added a `type` argument to the `conversations.create` method, with a default that matched the existing behaviour so as not to break existing implementations

Update create conversations endpoint with 2.6 typing

---

test/integration/companies.test.ts
test/integration/conversations.test.ts
test/integration/dataAttributes.test.ts
test/integration/messages.test.ts

This pull request removes the tagId parameter from the companies test file, fixes the admin filtering in the conversations.test.ts file, and refactors the adminId assignment in the messages.test.ts file. These changes improve the efficiency and readability of the code.

Fix tests on Node SDK

---

lib/contact/contact.types.ts

There is a typo in the Contacts object
Fix the spelling mistake
```opted_out_subscription_tyes``` => ```opted_out_subscription_types```

Fix type in ContactObject: opted_out_subscription_tyes

---

lib/company.ts
test/integration/companies.test.ts
test/unit/company.test.ts

Makes it clearer that this endpoint uses the Intercom ID for a company,
and not the companyID that is optionally provided during creation
closes #356
NB: This is a *breaking* change

Update the company.update method

---

REPO_OWNER

updating the repo owner as part of handing stuff to data interop

updating the repo owner
