intercom/intercom-node

README.md, package.json
=> Polish readme and pin unirest dependency

.travis.yml, package.json
=> Test on node 4.0

lib/bulk.js, lib/client.js, lib/contact.js, test/admin.js, test/bulk.js, test/client.js, test/company.js, test/contact.js, test/conversation.js, test/counts.js, test/event.js, test/index.js, test/message.js, test/note.js, test/segment.js, test/tag.js, test/user.js
Just re-applied changes on master, faster than fixing merge conflicts after the Promise additions.
=> Use ES6 let/const for block-scope and readability

test/admin.js, test/bulk.js, test/client.js, test/company.js, test/contact.js, test/conversation.js, test/counts.js, test/event.js, test/index.js, test/message.js, test/note.js, test/segment.js, test/tag.js, test/user.js
replacement of #44, this is a bit subjective though- i like them, not everyone would agree with this. it's not a performance concern though since arrow fn have been optimized in v8 node 4.x.x and also you're using babel so it's es5 anyways (they're ALMOST as fast, no significant difference- just an extra bind)
=> prefer arrows for lexical binding and expressiveness

gulpfile.js, package.json
This solves the build error seen on `master` if you re-run Travis CI (or `npm test` after a fresh `npm install`, clean node_modules and whatnot before if you want to test locally). It also solves the problem troubling #54 ( @bsiddiqui you will need to merge master to your branch once this PR is merged )
=> Upgrade gulp nsp

README.md, lib/user.js, test/user.js
https://github.com/intercom/intercom-node/issues/58
=> Add more finds

lib/index.js, test/index.js
https://github.com/intercom/intercom-node/issues/56
=> Adds Secure Mode calculator

lib/user.js, test/user.js
As documented: https://doc.intercom.io/api/#delete-a-user
=> Allow delete user by user_id or email

.travis.yml
Add stable node instead of hardcoding 4.
=> Add stable node

README.md, lib/client.js, test/contact.js
https://github.com/intercom/intercom-node/issues/69
=> Alias contacts as leads

README.md
This feature works in the node library, should be documented
=> Documentation for lead creation feature with attributes

README.md
Adding docker image for customer to use
=> Intercom docker v1

package.json
related to https://github.com/intercom/intercom-node/issues/107
=> update insecure unirest

README.md, lib/admin.js, test/admin.js
related to https://github.com/intercom/intercom-node/pull/103
=> add admins.me method

README.md, lib/client.js, lib/visitor.js, test/visitor.js
Add support for the visitors endpoint
https://developers.intercom.io/reference#visitors
=> Add /visitors endpoint

README.md, lib/event.js, test/event.js
Simple mapping to the `GET /events` endpoint of the Intercom API.
=> Add events listBy method

README.md, lib/user.js, test/user.js
Customers seem confused by this from time to time. While it's essentially the same request, it helps to have the alias. I also updated the readme 
@choran this look ok? 😬
=> Add an update alias for user 

README.md
* I added a note about the API key deprecation which is present on the site.
* I included the links to the documentation.
* `README.md`
* I missed it the first time so hopefully it will be more obvious to the next person :)
=> API Key Deprecation notice in documentation

README.md
=> Changes to personal access token names and API removal

README.md, lib/company.js, test/company.js
=> update companies.listUsers method by company_id

README.md
Related to #179 
Need to add example to find admins in README
=> Adding find example for admins

README.md
=> Link to correct docker image

lib/client.js, test/errors.js
Fix the issue outlined in https://github.com/intercom/intercom-node/issues/200.
=> Instantiate client `Error`s with the correct message.

.circleci/config.yml
I included the wrong directory in the last PR. 
This sets the correct working directory to the config.
=> Fixing directory in circle config

.travis.yml
Removing travis as part of our ci step
=> Remove travis ci

README.md
While looking at the README, I found some URLs that are broken/outdated. This PR fixes those URLs.
=> Fix broken URLs in README.md

gulpfile.js, package.json, yarn.lock
Fixes https://github.com/intercom/intercom/issues/141597
=> Remove gulp-nsp

README.md, lib/client.js, lib/customer.js, test/customer.js
https://developers.intercom.com/intercom-api-reference/v0/reference#customers
Add search feature for customer
=> Add customer search

.circleci/config.yml, package.json, yarn.lock
This repo's packages are a little old. This pr aims to update the packages that are used here to be more inline with modern updates of the packages
=> Update various npm packages

package.json
Bumped version before publishing which caused an extra bump while publishing
=> bump to released version 2.11.2

README.md
=> Convert id properties from snake_case to camelCase

README.md, lib/client.ts, lib/index.ts, lib/visitor.ts, lib/visitor/visitor.types.ts, test/visitor.ts
Why are you making this change?
=> Add Visitor

README.md, lib/message.ts, test/integration/messages.test.ts
See #318
- Added "createConversationWithoutContactReply" as optional parameter to messages.create
- Added messages.test.ts to Integrations test suite
- Added example message to documentation
=> Create conversation without contact reply

lib/contact.ts, test/unit/contact.test.ts
=> Permit creating leads with email

lib/contact.ts
Closes https://github.com/intercom/intercom-node/issues/313
Closes https://github.com/intercom/intercom-node/issues/314
Add `email` to `UpdateContactData` and the `update` command
=> add email to contact update

README.md, lib/client.ts, lib/dataExport.ts, lib/dataExport/dataExport.types.ts, lib/phoneCallRedirect.ts, lib/phoneCallRedirect/phoneCallRedirect.types.ts, test/integration/dataExport.test.ts, test/integration/phoneCallRedirect.test.ts
Data_exports
```
> start()
Promise { <pending> }
> {
job_identifier: 'kby097a3e7o7rw10',
status: 'pending',
download_url: '',
download_expires_at: ''
}
>
> start()
Promise { <pending> }
> {
job_identifier: 'kby097a3e7o7rw10',
status: 'no_data',
download_url: '',
download_expires_at: ''
}
```
Phone 
``` 
> start()
Promise { <pending> }
{
type: "phone_call_redirect",
url: "redacted",
}
```
=> Add switch api + data export api

lib/dataExport.ts, lib/phoneCallRedirect.ts, test/integration/dataExport.test.ts
First ship broke some typescript integration tests. 
This pr fixes errors that have occurred.
=> Fix typescript errors

README.md, package.json
Why are you making this change?
=> Update package to version 3.2

package.json
for https://github.com/intercom/intercom-node/issues/338
Bad publish sorry all
=> Update to 3.2.1 due to bad npm publish

package.json
=> Update intercom-node to 4.0.0

README.md
=> Documentation Error

.circleci/config.yml, package.json, test/integration/admins.test.ts, test/integration/articles.test.ts, test/integration/companies.test.ts, test/integration/contacts.test.ts, test/integration/conversations.test.ts, test/integration/counts.test.ts, test/integration/dataAttributes.test.ts, test/integration/dataExport.test.ts, test/integration/events.test.ts, test/integration/helpCenter/collections.test.ts, test/integration/helpCenter/sections.test.ts, test/integration/integration.test.ts, test/integration/messages.test.ts, test/integration/notes.test.ts, test/integration/phoneCallRedirect.test.ts, test/integration/segments.test.ts, test/integration/subscriptions.test.ts, test/integration/tags.test.ts, test/integration/teams.test.ts, test/integration/visitors.test.ts
The test infra is kind of janky, so cleaning it up
- Move us to a support circleCI image
- Compile the TS for tests
- update paths to test the TS
- fix two broken tests
=> Fix test infra

lib/company.ts, test/integration/companies.test.ts, test/unit/company.test.ts
Reverts intercom/intercom-node#375
=> Revert "Update the company.update method"

README.md
This pull request updates the README.md file to include information about the current maintenance mode of the Intercom Node SDK. It states that new feature requests are not being accepted and active development is on hold. This information is important for users and potential contributors to be aware of the current status of the SDK.
=> Update README.md with maintenance mode information

.fernignore
This will prevent files that should not be modified or deleted from being modified or deleted when generating the SDK with Fern.
=> Add .fernignore file
